version: '3.2'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./cypress-image-diff-screenshots:/code/cypress-image-diff-screenshots
      - ./cypress-image-diff-html-report:/code/cypress-image-diff-html-report
      - ./cypress/videos:/code/cypress/videos
